### ISSUE TITLE
Exported data - first row is NA in all columns

### ISSUE THREAD

**Issue by josefbruna** [environmentalinformatics-marburg/tubedb#9] opened 2021-02-03 16:00 UTC
in any export, the first row with data of each plot is NA (even if it actually measured).
in a file with multiple plots, this happens at every first row of each plot
this problem is also reproducible with the example data

**Comment by swoellauer** [comment] 2021-02-20 11:21
The cause of this error was a bug in the step-range data quality check. Now at the beginning of a time series this checks starts filtering if there are enough elements in the past, not at the first element.  It should be fixed now.

**Closed** 2021-02-20 11:21 UTC
